### ISSUE TITLE
NLTopo app: ook RD/EPSG:28992 ondersteunen

### ISSUE THREAD

**Issue by justb4** [map5nl/map5#11]
NLTopo app heeft nu Google/OSM tiling. Daardoor wat "distortion". RD zou meer voor de hand liggen, evt zelfs een switch tussen de 2 projecties. 

@jwva schreef: "Ik zou alleen in de app zo graag voor 28992 willen kunnen kiezen... dat de fiets- en wandelroutes dan (nog) niet bruikbaar zijn zou ik voor lief nemen.
Nu verdwijnen er door afrondingen in herberekeningen toch pixels, zie het grid in de attachment. Effect is denk ik vooral hier zichtbaar omdat we de LuFo 800 nog niet hebben, maar toch. Is CRS-setting als optie toe te voegen in de app?"

Kost wat ontwikkeltijd: is nl Leaflet, geen OpenLayers. Is op zich eerder gedaan bijv. http://app.nlextract.nl/ot/opentopord.html, maar i.c.m. (WGS84) Geocoder wordt dit alweer lastiger maar aangezien we Nederlandse kaarten hebben is een NL projectie gewenst.

**Comment by jwva** [comment]
Toon a.u.b. ook doorlopend de muiscoordinaten in 't klein, links onderin naast de schaalbalk. 
Dat maakt het makkelijk voor gebruikers om een aparte URL te construeren voor een bepaalde plek in Nederland en die dan aan anderen te mailen of te embedden in tweets en zo. Je zou zelfs een "share this map location on social media" knopje kunnen maken onder de kaartlagenknop.
Nu zoomde ik in naar de Hunneschans bij het Uddelermeer, maar ik kan jou die locatie niet mailen als ik niet weet waar de muis staat. Dus voor WGS84 de (lat,lon) en voor 28992 de (rdx,rdy).

**Comment by justb4** [comment]
Daar had ik al aan gedacht, alleen: waar op het scherm? Alle hoeken zijn 
"vol". Ik denk meer aan de manier waarop OpenStreetMap dat doet: in de 
location bar:
http://www.openstreetmap.org/#map=19/52.24708/5.76405 (verschuif de 
kaart en zie de URL veranderen). Alleen dit is weer in strijd met issue 
#5, althans op mobiel. Maar er is wel iets te verzinnen. Ik ben nl van 
plan de hele app te herontwerpen.

**Comment by jwva** [comment]
Ik dacht linksonder bij de schaalbalk, zie bijv. nederland.risicokaart.nl (Flamingo).
In de location bar is zelfs nog handiger, dat maakt het “delen” van een bepaald huidig kaartbeeld veel simpeler. Zet dan ook het zoomlevel in de location bar.

**Comment by justb4** [comment]
Ja in location bar kan altijd (cross-browser) als "segment identifier". Ivm met twee projecties denk ik aan volgende conventie:

           #<projectie>/<basis_laag>/<zoom>/<x-coord>/<y-coord> bijv
           #rd/opentopo/11/rd_x/rd_y (in RD)
           #osm/openlufo/14/lon/lat of #osm/openlufo/14/rd_x/rd_y 

Coordinaten kunnen altijd in RD of lon/lat. Gezien het bereik van de x,y of lon/lat waardes is eenvoudig af te leiden wat bedoeld wordt.

**Comment by justb4** [comment]
Op http://app.test.map5.nl/nltopo staat vast een "sneak preview" van de RD-versie (nog zonder segment identifier). Met wandel/fietslagen uit PDOK!

**Comment by justb4** [comment]
Ok, de kaartcontext staat nu volgens bovenstaande conventie in de browser locatie-bar in http://app.map5.nl/nltopo. Hierdoor blijft zowel RD als OSM projectie ondersteund, default is RD. Zie ook http://www.map5.nl/toepassingen.html voor uitleg conventies. Voorbeelden, Romeins Fort in RD en OSM projectie:

http://app.map5.nl/nltopo/#rd/relief_struct/12/5.692633/52.28434

http://app.map5.nl/nltopo/#osm/relief_struct/17/5.692633/52.28434

Nog te doen:

- browser historie gaat mee in URL-segment (#...) wijzigingen waardoor de back-button het vorige kaartbeeld levert. Is niet altijd intuïtief. 
- support voor RD-coordinaten naast lon/lat

**Comment by justb4** [comment]
@jwva Er is nu support voor RD-coordinaten in de locatie-bar. Het maakt zelfs niet uit of de coordinaten aanvankelijk in Lon/Lat, Lat/Lon, x,y of y,x staan (in ons gebied is y altijd groter x). Afhankelijk van de projectie 'osm' of 'rd' worden de coordinaten in bijbehorende projectie in de locatie-bar afgebeeld.

Het laatste is nog de browser historie, want je kunt na aantal keren pan/zoom niet in een keer terug naar vorige pagina....

**Comment by justb4** [comment]
Nu deze sluiten (EPSG:28992 wordt nu gesupport) en apart issue #14 voor browser historie aanmaken.
