### ISSUE TITLE
Map5 viewer openen met pre-selected map layer

### ISSUE THREAD

**Issue by jwva** [map5nl/map5#12]
Ik heb nu alleen één basis URL voor de Map5 kaartviewer, die opent in de eerste kaartlaag (OpenTopo). Als ik iemand wil wijzen op een andere kaartlaag, dan moet ik diegene instrueren om rechts op het kaartlagen icoontje te gaan staan en dan die kaartlaag te kiezen. Omslachtig!
Kan de Map5 viewer ook geopend worden met een specifiek meegegeven kaartlaag?

Het zou prettig zijn als deze directe URLs/parameters dan worden meegegeven als klikbare kopjes van de verschillende kaartlagen op http://www.map5.nl/kaarten.html .

**Comment by justb4** [comment]
On 19-05-15 17:36, jwva wrote:
> Ik heb nu alleen één basis URL voor de Map5 kaartviewer, die opent in de
> eerste kaartlaag (OpenTopo). Als ik iemand wil wijzen op een andere
> kaartlaag, dan moet ik diegene instrueren om rechts op het kaartlagen
> icoontje te gaan staan en dan die kaartlaag te kiezen. Omslachtig!
> Kan de Map5 viewer ook geopend worden met een specifiek meegegeven
> kaartlaag?
>
> Het zou prettig zijn als deze directe URLs/parameters dan worden
> meegegeven als klikbare kopjes van de verschillende kaartlagen op
> http://www.map5.nl/kaarten.html .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/map5nl/map5/issues/12>.
>
Dat zou idd handig zijn net als coordinaten en zoomlevel.

**Comment by justb4** [comment]
Gedaan! Zie http://www.map5.nl/kaarten.html 
De NLTopo app kan iha met een `base_layer` parameter geopend worden die de achtergrondkaart bepaalt. Bijv
http://app.map5.nl/nltopo/?base_layer=relief_struct. Geldige waarden voor `base_layer`: 

                    "OSM-TopoMap":  'osm_eu'
                    "OpenTopo": 'opentopo'
                    "OpenLufo": 'openlufo'
                    "Reliëf Struct (AHN2)":  'relief_struct'
                    "Historisch NL 1900":  'bonne_1900',
                    "Historisch NL 1925": 'bonne_1925'
                    "Historisch NL 1949": 'bonne_1949'
                    "Historisch NL TMK 1850": 'tmk_1850'
 
Een simpele uitbreiding zou nog zijn om lat/lon of x/y en zoom mee te geven om specifiek kaartbeeld (locatie, zoom) op te roepen. Hiervoor evt een nieuw issue openen.
