### ISSUE TITLE
NLTopo app: coordinaat- en zoom parameters kunnen meegeven

### ISSUE THREAD

**Issue by justb4** [map5nl/map5#13]
Handig: kun je meteen naar beeld op kaart gaan tezamen met achtergrond, bijv het Romeinse Fort bij Speuld op de Veluwe:

http://app.map5.nl/nltopo/?base_layer=relief_struct&lon=5.692&lat=52.284&zoom=17

params zijn: `lat`, `lon` en `zoom` (later nog rd_x, rd_y met issue #11 )

@jwva Is dus al gedaan, voor zichtbaarheid in dit issue verwerkt.

**Comment by justb4** [comment]
Gedaan, ik blijf dat Romeinse Fort intrigerend vinden:

![relief_struct_speuld_romfort](https://cloud.githubusercontent.com/assets/582630/7756866/4ad9b492-fffe-11e4-93da-e4a315594992.png)

**Comment by justb4** [comment]
De conventie hierboven wordt nog wel ondersteund maar de voorkeur is deze nieuwe conventie:

In location bar kan altijd (cross-browser) als "segment identifier". Ivm met twee projecties denk ik aan volgende conventie:

           #<projectie>/<basis_laag>/<zoom>/<x-coord>/<y-coord> bijv
           #rd/opentopo/11/rd_x/rd_y (in RD)
           #osm/openlufo/14/lon/lat of #osm/openlufo/14/rd_x/rd_y 

Coordinaten kunnen altijd in RD of lon/lat. Gezien het bereik van de x,y of lon/lat waardes is eenvoudig af te leiden wat bedoeld wordt.

Ok, de kaartcontext staat nu volgens bovenstaande conventie in de browser locatie-bar in http://app.map5.nl/nltopo. Hierdoor blijft zowel RD als OSM projectie ondersteund, default is RD. Zie ook http://www.map5.nl/toepassingen.html voor uitleg conventies. Voorbeelden, Romeins Fort in RD en OSM projectie:

http://app.map5.nl/nltopo/#rd/relief_struct/12/5.692633/52.28434

http://app.map5.nl/nltopo/#osm/relief_struct/17/5.692633/52.28434

Nog te doen:

- browser historie gaat mee in URL-segment (#...) wijzigingen waardoor de back-button het vorige kaartbeeld levert. Is niet altijd intuïtief. 
- support voor RD-coordinaten naast lon/lat

(was per ongeluk in issue #11 terecht gekomen)

**Comment by jwva** [comment]
Waarom werkt
http://app.map5.nl/nltopo/#rd/opentopo/14/145000/455000
niet?
Dit is een <projectie>/<basis_laag>/<zoom>/<rd_x>/<rd_y>

**Comment by justb4** [comment]
Omdat RD nog niet geïmplementeerd is. Daarom is dit issue nog open. Zie ook "Nog te doen:" hierboven.

**Comment by jwva** [comment]
Ah, dank. Ik ging uit van je opmerking dat het bepalen van coördinatenstelsel goed is af te leiden uit de getallen die daar worden ingevuld. Ik had even niet gelezen dat RD getallen nog niet geïnterpreteerd worden… :-)

**Comment by justb4** [comment]
RD kan nu meegegeven, bijv:

http://app.map5.nl/nltopo/#rd/opentopo/14/145000/455000 maar ook
http://app.map5.nl/nltopo/#rd/opentopo/14/5.241313/52.08318 of
http://app.map5.nl/nltopo/#rd/opentopo/14//52.08318/5.241313 http://app.map5.nl/nltopo/#osm/opentopo/16/145000/455000 of
http://app.map5.nl/nltopo/#osm/opentopo/16/455000/145000 etc

**Comment by jwva** [comment]
Mooi werk, complimenten! Hiermee hebben we een echt flexibele viewer waarmee je kaartbeelden heel precies kunt duiden en delen via social media. Ik zal de komende tijd eens wat tamtam gaan maken op verscheidene Linkedin groepen.
