### ISSUE TITLE
Kaartlagenmenu: volgorde kaarten wijzigt steeds

### ISSUE THREAD

**Issue by jwva** [map5nl/map5#15]
In de app in de kaartlagenmenu is de volgorde van de kaartlagen aan verandering onderhevig. Kan verwarrend werken. Voorstel: actuele kaartlagen alfabetisch sorteren A-Z, historische kaartlagen chronologisch sorteren oud-nieuw.

**Comment by justb4** [comment]
Vreemd, ik kan dit niet reproduceren. Althans op Mac in Chrome en Safari. Is erg lastig op te lossen want zit diep in third party library Leaflet. Daar zitten de lagen in een hashmap dus idd zou ik een willekeurige volgorde verwachten.

**Comment by jwva** [comment]
Lijkt me geen prio #1 show-stopper, dus als het veel werk is, laat dan maar zitten.

**Comment by justb4** [comment]
Maar vreemd, gebeurt dit alleen in IE dus?

**Comment by jwva** [comment]
Nee, ook in Chrome. Het gebeurt als je van een bepaalde kaartlaag veel locaties achtereen opzoekt, dan komt die kaartlaag bovenaan de lijst te staan.

**Comment by justb4** [comment]
Zie nog steeds niets. Wat is "veel locaties achtereen opzoekt"?

**Comment by jwva** [comment]
Veel verschillende adressen achtereen via de zoekbox.

**Comment by justb4** [comment]
Hmm, nog steeds niet, kan me wel uit verleden zoiets herinneren, maar we laten het even voor nu dan. Heb je gezien dat issue #16 (Marker) is opgelost?

**Comment by jwva** [comment]
Ja, goed opgelost zo met die marker!
