### ISSUE TITLE
Druppel van geolocator is niet te verwijderen

### ISSUE THREAD

**Issue by jwva** [map5nl/map5#16]
Zodra via text search een locatie is gevonden op de kaart, verschijnt daar een druppel.
Die is echter niet meer te verwijderen.
Voorstel: druppel weer verwijderen zodra daar op geklikt wordt, of verwijderen als de zoekbox leeg wordt gemaakt.

**Comment by justb4** [comment]
Is gefixed, alleen iets anders: als je op marker klikt krijg je de text popup. Zoekbox leegmaken leek mij ook niet intuïtief. De huidige oplossing werkt ook mobiel gemakkelijk.

Probeer anders uit op: http://app.map5.nl/nltopo

Ik sluit issue. Indien niet ok, heropenen.
