### ISSUE TITLE
Entrance ramp #35 A67 Netherlands

### ISSUE THREAD

**Issue by SeniorPeer** [map5nl/map5#17]
Approx half a year ago the entrance ramp #35 Someren of the highway A67 been extended to the east (direction Venlo). Next to the existing bridge a new one has been constructed and the entrance ramp now is about 300m longer.

**Comment by justb4** [comment]
This is not a map5/opentopo issue but an OpenStreetMap issue where the mapping data is maintained. You can change the data in OpenStreetMap http://www.openstreetmap.org and/or notify them via http://wiki.openstreetmap.org/wiki/NL:Notes: . Your changes will then be present in the next 2016 release of OpenTopo in map5.nl.

**Comment by justb4** [comment]
Hoi,

Ik zag dat Google deze afrit bij Someren al heeft aangepast, en op OpenStreetMap nog niemand, dus ik heb 'm maar even ingetekend. Kleine moeite.

Met hartelijke groet,

Jan-Willem van Aalst
