### ISSUE TITLE
NLTopo App: HTTPS ondersteuning tbv geolocatie

### ISSUE THREAD

**Issue by justb4** [map5nl/map5#19]
geolocatie/GPS knop werkt niet meer in NLTopo App (http://app.map5.nl/nltopo/) omdat o.a. Chrome sinds enige tijd alleen nog `HTTPS` vereist: https://developers.google.com/web/updates/2016/04/geolocation-on-secure-contexts-only
Oplossing is om NLTopo en mogelijk andere apps via `HTTPS`  te laten serveren.

De error die nu getoond wordt staat hieronder:

![geolocation-error-info](https://cloud.githubusercontent.com/assets/582630/16518195/d8663e52-3f81-11e6-942b-7d48d5b63c0a.png)

Met dank aan Leon voor melden en plaatje.

**Comment by justb4** [comment]
SSL-certifcaat is aangeschaft, nu in test-fase. Verwacht rond 1 nov 2016 in productie.

**Comment by justb4** [comment]
Dit betekent ook dat kaartlagen zowel in HTTP als HTTPS kunnen worden opgevraagd. Op dit moment wordt alleen de apps naar HTTPS geforceerd.

**Comment by jwva** [comment]
Kaartbeeld ziet er goed uit in Chrome op HTC-10 smartphone. Alleen als ik van kaart wissel, dan blijft het kaartwissel-menu in beeld en krijg ik ook (haast) niet meer weg.

**Comment by justb4** [comment]
Het gaat in dit issue even of HTTPS goed werkt. Dat is nl niet altijd evident gezien de variëteit in SSL-opties i.c.m. devices en versies en "mixed-content". Open anders een nieuw issue voor suggesties/problemen met de NLTopo app zelf.

**Comment by justb4** [comment]
SSL/HTTPS support is nu compleet. Kaartlagen kunnen zowel via HTTP als HTTPS worden opgevraagd. De NLTopo app zal altijd naar HTTPS switchen, m.n. omdat allen met HTTPS GPS werkt in meeste browsers: zie https://app.map5.nl/nltopo. Graag andere UI-problemen openen in aparte issues. 

Hieronder nog het rapport van QualSys SSL labs, een A+ rating. Dit betekent dat map5.nl HTTPS compatibel is met ongeveer alle clients.

![ssl-report](https://cloud.githubusercontent.com/assets/582630/20246111/2854109a-a9b0-11e6-88ea-b3e78002a776.jpg)
