### ISSUE TITLE
adressen lijst

### ISSUE THREAD

**Issue by emureau** [map5nl/map5#20]
het tekenen van een polygoon waar je vervolgens een CSV export zou kunnen doen van alle plaatsnaam, adres, huisnr, postcode en vloeroppervlakte zou zeer handig zijn.
Wij maken adreslijsten van omwonenden bij bouwprojecten nu nog handmatig.

**Comment by justb4** [comment]
De context is mij niet direct duidelijk: map5.nl gaat over leveren webdiensten voor rasterkaarten. Er zijn een paar voorbeeld applicaties, neem dus aan dat vraag betrekking heeft op KadViewer (http://kadviewer.kademo.nl). Aldaar kan bijna aan gehele vraag voldaan worden. Volg deze stappen:

- ga naar http://kadviewer.kademo.nl
- activeer de kaartlaag (via mappen links): `PDOK/BAG/BAG Adressen`
- zoom in naar gebied, adressen worden zichtbaar als oranje stippen
- open zoekformulier popup window via "verrekijker icoon" bovenaan (links van adreszoeker)
- kies uit "Zoeken:" dropdown-box binnen zoekwindow het zoekformulier *"Zoek door geometrieën te tekenen"*
- kies een tekentool, bijv bounding box (default) of polygoon (afsluiten met dubbel-klik) en teken
- zie resultaten in tabel
- klik *"Download:"* binnen zoekformulier met *als Comma Separated Values (CSV)*  
- download/open als CSV!
 
De adressen komen van PDOK. Helaas bevatten die geen vloeroppervlak. U kunt een verzoek hiervoor indienen bij beheerPDOK@kadaster.nl. Oppervlak is ook eigenschap van Pand. Is evt vraag voor NLExtract support (http://nlextract.nl) die BAG (CSV) ter beschikking stelt.

Zie ook plaatje onder. 
![adressearch](https://cloud.githubusercontent.com/assets/582630/16725478/ba4ed662-4757-11e6-954d-e7356c6ef13b.jpg)

Ik denk dat hiermee issue binnen mogelijkheden KadViewer en PDOK gesloten kan worden.

**Comment by emureau** [comment]
Hartelijk dank voor de vlugge en volledige antwoord. Dit is precies wat ik zoek.

Mvgr.
Etienne Mureau

Van: Just van den Broecke [mailto:notifications@github.com]
Verzonden: maandag 11 juli 2016 11:12
Aan: map5nl/map5 <map5@noreply.github.com>
CC: Etienne Mureau <Emureau@bouwrisk.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [map5nl/map5] adressen lijst (#20)


De context is mij niet direct duidelijk: map5.nl gaat over leveren webdiensten voor rasterkaarten. Er zijn een paar voorbeeld applicaties, neem dus aan dat vraag betrekking heeft op KadViewer (http://kadviewer.kademo.nl). Aldaar kan bijna aan gehele vraag voldaan worden. Volg deze stappen:

  *   ga naar http://kadviewer.kademo.nl
  *   activeer de kaartlaag (via mappen links): PDOK/BAG/BAG Adressen
  *   zoom in naar gebied, adressen worden zichtbaar als oranje stippen
  *   open zoekformulier popup window via "verrekijker icoon" bovenaan (links van adreszoeker)
  *   kies uit "Zoeken:" dropdown-box binnen zoekwindow het zoekformulier "Zoek door geometrieën te tekenen"
  *   kies een tekentool, bijv bounding box (default) of polygoon (afsluiten met dubbel-klik) en teken
  *   zie resultaten in tabel
  *   klik "Download:" binnen zoekformulier met als Comma Separated Values (CSV)
  *   download/open als CSV!

De adressen komen van PDOK. Helaas bevatten die geen vloeroppervlak. U kunt een verzoek hiervoor indienen bij beheerPDOK@kadaster.nl<mailto:beheerPDOK@kadaster.nl>. Oppervlak is ook eigenschap van Pand. Is evt vraag voor NLExtract support (http://nlextract.nl) die BAG (CSV) ter beschikking stelt.

Zie ook plaatje onder.
[adressearch]<https://cloud.githubusercontent.com/assets/582630/16725478/ba4ed662-4757-11e6-954d-e7356c6ef13b.jpg>

Ik denk dat hiermee issue binnen mogelijkheden KadViewer en PDOK gesloten kan worden.

**Comment by justb4** [comment]
Stond nog open, is naar tevredenheid beantwoord, kan gesloten.
