### ISSUE TITLE
Missende bruggetjes bij bepaalde zoomniveaus

### ISSUE THREAD

**Issue by niekvanruler** [map5nl/map5#35]
Op
https://app.map5.nl/map5topo/sidebyside/#map=11.00/205035.10/565348.38/0/4 
mist een bruggetje. Bij opentopo zie ik die wel.
Ook op andere locaties missen de bruggetjes.
Als je verder inzoomt komt die wel tevoorschijn.
![map5_brug](https://user-images.githubusercontent.com/10760567/207019944-1fd445b3-3dbf-4a6d-8c1b-028bc15a37e5.PNG)

**Comment by justb4** [comment]
@niekvanruler bedankt voor deze terugkoppeling! Is toevallig een van onze aandachtspunten: het betreft hier een dedicated fietspad (`highway=cycleway`). Voor `highway=path|track` hadden we op zoom 11 ook eerst geen 'Style'. Voor fietspaden i.h.a. ligt er een intern issue sowieso. We pakken dit op!

**Comment by justb4** [comment]
Bleek nog iets meer 'involved', hebben verschillende Styles aangepast, hieronder resultaat (links is nieuw, rechts is oud in plaatjes) for zoom 10 en 11 op onze test server:

![image](https://user-images.githubusercontent.com/582630/207079429-bd4fd143-7581-4f9c-9cca-1ab1b1211bea.png)

We willen ook nog fietspaden prominenter maken/kleur geven.

**Comment by justb4** [comment]
@niekvanruler volgens ons opgelost, indien eens (wel even je browser cache legen), graag issue sluiten.

**Comment by niekvanruler** [comment]
Het is opgelost.
Mooie opvolger van opentopo!
