### ISSUE TITLE
Beek is een zwart streepje ipv bijvoorbeeld blauw

### ISSUE THREAD

**Issue by niekvanruler** [map5nl/map5#36]
https://app.map5.nl/map5topo/sidebyside/#map=9.00/204527.67/564595.56/0/4

Bij bepaalde zoomlevels rondom 9 (8/9/10) is het beekje een zwart streepje.
![image](https://user-images.githubusercontent.com/10760567/211487842-c769cea6-aacd-4cc6-89e4-e9c32256e667.png)

**Comment by justb4** [comment]
@niekvanruler Je bedoelt denk ik en rood streepje. Ja was mij ook opgevallen bijv in Muiden:

![image](https://user-images.githubusercontent.com/582630/211659357-57178789-9982-4b4a-8497-cf164d9bb6b9.png)

Denk dat dit, kijk even naar @nieneb, een per-ongeluk ingecheckte Style is, ooit bedoeld voor debugging.

**Comment by niekvanruler** [comment]
Het is denk ik inderdaad rood, maar ik ben kleurenblind en in eerste instantie lijkt het zwart voor mij.

**Comment by justb4** [comment]
Gefixed, inderdaad een paar stijlen stonden op rood, nu aangepast, binnenkort in nieuwe rendering, bijv :

![image](https://user-images.githubusercontent.com/582630/212086691-33af7324-3153-4e1f-82bb-5f4ae79ed3f3.png)

**Comment by justb4** [comment]
@niekvanruler  
En een nieuwe rendering gedaan. Plan in productie week 13 feb 2023. Met o.a. BAG Panden en BGT (Weg+Water op zoom 13) Nu op Test Server:
https://app.test.map5.nl/map5topo/sidebyside/#map=9.00/204527.67/564595.56/0/4
Denk dat we deze kunnen sluiten.

**Comment by niekvanruler** [comment]
Is inderdaad opgelost op de testomgeving.
