### ISSUE TITLE
IJmuiden harbour water error

### ISSUE THREAD

**Issue by KlaasVisual** [map5nl/map5#39]
De haven van IJmuiden (water in binnenland maar sluit aan bij zee) is verkeerd weergegeven.
- vanaf zoom 10
- vreemde misvorming hoogtemodel rond kades
- echt binnenwater wel correct

<img width="1958" alt="Scherm­afbeelding 2023-07-25 om 10 15 33" src="https://github.com/map5nl/map5issues/assets/140493507/40293fe2-aee5-4ed1-ba23-2d5481027e55">

**Comment by justb4** [comment]
Bevestigd en dank hiervoor!
 De reden hiervoor is ook duidelijk en zal in volgende versie, wie weet tussenversie, gerepareerd worden.

De voornaamste reden is dat voor alle water dat "zee" is, OpenStreetMap polygonen worden gebruikt. Dit is omdat in de "hogere-zoom" basisregistraties, althans in Top10NL (zoom 10-12) en BGT (zoom 13) de zee-polygonen niet volledig zijn/leken en natuurlijk dubbel-op zouden zijn met OSM.

De OpenStreetMap zee-polygonen houden zich echter niet geheel aan wat wij als zee beschouwen. In de laatste map5.nl nieuwsbrief nummer 11, werd al de Oosterschelde genoemd (helaas is die op Z13 ook "dicht" zie ik net). Deze is wel zee, maar zit niet in de OSM zee-polygonen en is extra toegevoegd op 10-13. Dat probleem was goed zichtbaar tijdens ontwikkeling. Hetzelfde probleem heeft u ook hier geconstateerd, mogelijk zal het op meer plekken zijn. Op zoom 0-9 gaat het wel "goed" omdat daar ofwel algemeen "water" uit OSM aanwezig is (1-5) en water, inclusief zee, uit Top50NL (6-9). Top50 lijkt gek genoeg vollediger namelijk.
Dus de oplossing wordt om op zoom 10-13 toch bepaalde zee-waterdelen uit Top10NL (10-12) en BGT (13) mee te nemen.

Doordat er in feite geen vlakgevuld kaartbeeld op 10-13 is, worden de artefacten/randen uit de AHN reliëf zichtbaar. Dit is ook een bekend probleem, zie issue #38  dat we gaan oplossen, mogelijk door overstap van AHN3 naar AHN4.

**Comment by KlaasVisual** [comment]
Wat een werk! Ik vermoedde al een onenigheid over ‘bijna zee’…Veel succes!Klaas van der Veen

**Comment by justb4** [comment]
Opgelost, wel even de browser cache legen. 
![image](https://github.com/map5nl/map5issues/assets/582630/2b7e4059-320f-438f-adb5-ae9dafb368d0)
