### ISSUE TITLE
raster

### ISSUE THREAD

**Issue by niekvanruler** [map5nl/map5#41]
In PAN (https://portable-antiquities.nl/) willen we map5 als achtergrond gebruiken.
Op de Noordzee gebruiken we het ncp grid (https://www.nationaalgeoregister.nl/geonetwork/srv/api/records/31ea7a8d-a6e4-4407-ab59-35afe321b5f0) om vondsten op de publiekssite in een vak te stoppen, zodat de exacte vindplaats niet bekend is.
Op land worden vondsten in een gemeente geplaatst

Bijbepaalde zoomniveaus (>=5) wordt er een grid zichtbaar wat voor verwarring zorgt zie de afbeelding
In zwart het ncp grid
![image](https://github.com/map5nl/map5issues/assets/10760567/0aa0332c-981b-48d4-8529-e050cb71c5c2)

Hoe zou dit opgelost kunnen worden?
Ik heb al gekeken naar de simpele versie van map 5, daar ontbreekt het grid, maar die heeft weer wat minder detail als je inzoomt op een akker. Die details kunnen soms handig zijn voor de bepaling van de juiste lokatie.

**Comment by justb4** [comment]
Het grid dat zichtbaar wordt op RD zoom >=5 is het officiële Kadaster 1km RD grid. De coordinaten zijn steeds horizontale en verticale lijnen die op 1000-tallen van meters liggen, beginnend linksonder op X,Y 10000, 300000 (bij Parijs). 
Per zoom-nivo worden ze naar rato weergegeven. Op de klassieke papieren kaarten staan deze ook al. Dit hoort echt bij een topografische kaart, zie ook Kadaster TopRaster zoals in screenshot:

![image](https://github.com/map5nl/map5issues/assets/582630/75506160-7483-47fa-b0d9-aacb8adf392c)

Ze zijn licht van kleur ook niet teveel te interfereren. De NCP grid zijn gebaseerd op graden, logisch dat dit niet overeenkomt. 

We kunnen ze niet snel verwijderen. Dit is natuurlijk lastig voor een rasterkaart als achtergrondkaart. Zo was er een klant die een toepassing met bomen had, en liever de bomen van de kaart verwijderd zou zien...

Voor gedeelte op zee zou je nog een 'overlay' kunnen maken met de RD gridlijnen in dezelfde kleur als de zee. Ik kan dat NL grid bestand (GeoPackage of SQL) zee kleur wel leveren.

**Comment by niekvanruler** [comment]
Hoi Just,

Ik heb het al anders opgelost.
Het NCP-grid laad ik in via een JSON bestand.
De achtergrondkleur van het NCP-grid heb ik gelijk gemaakt aan de kleur van
de zee.
Hierdoor zie je het RD grid niet mee op de zee.
Bedankt voor het meedenken.

Groeten,
Niek


Op wo 27 sep 2023 om 15:18 schreef Just van den Broecke <
***@***.***>:
