### ISSUE TITLE
In- en uitzoomen met + en -

### ISSUE THREAD

**Issue by 501Ghost** [map5nl/map5#42]
Het zou fijn zijn om in de demo in- en uit te kunnen zoomen met de  + en - knoppen.

**Comment by justb4** [comment]
Welke demo? Kun je URL geven? Meeste demo's zijn OpenLayers, moet wel te doen zijn.

**Comment by 501Ghost** [comment]
Ik kijk nu naar https://app.map5.nl/map5topo/full/

**Comment by justb4** [comment]
Moet nu kunnen in beide demo apps:
https://app.map5.nl/map5topo/sidebyside/ en
https://app.map5.nl/map5topo/full/
Browser herladen ivm cache en focus op de kaart leggen.

**Comment by 501Ghost** [comment]
Werkt perfect! 😃
