### ISSUE TITLE
Gebruik een apart icoon voor stadspoorten

### ISSUE THREAD

**Issue by 501Ghost** [map5nl/map5#46]
Voor meerdere historische (OSM-)objecten wordt nu dezelfde icoon gebruikt, bijv. voor `historic=castle` en `historic=city_gate`.

Zie als voorbeeld het centrum van IJsselstein waar de vesting en 2 stadspoorten op OSM staan: 
![image](https://github.com/map5nl/map5issues/assets/61314579/f8c01b4b-86b2-48db-a51f-e33ad8e5e7b3)

Om een duidelijk onderscheid te maken en mensen niet het idee te geven dat er meerdere kastelen naast elkaar staan, is het beter om voor stadspoorten een apart icoon te gebruiken. Zie ook https://github.com/organicmaps/organicmaps/issues/6241 voor dezelfde openstaande issue in de repo van Organic Maps.

P.s. Je kunt ook overwegen om stadspoorten pas op een iets hoger zoomniveau te renderen. Stadspoorten zijn namelijk minder prominent dan kastelen.

**Comment by justb4** [comment]
Done, en stadspoorten verschijnen nu pas op zoom 15 (ipv 13).
![image](https://github.com/map5nl/map5issues/assets/582630/d16b78ad-7660-45ab-8024-1e62f74d0c94)

**Comment by 501Ghost** [comment]
Da's een hele verbetering :D

**Comment by justb4** [comment]
Over en sluiten?

**Comment by 501Ghost** [comment]
Zekers 👍
