### ISSUE TITLE
Render een icoon voor windmolens

### ISSUE THREAD

**Issue by 501Ghost** [map5nl/map5#48]
Een echte kaart van Nederland is natuurlijk niet compleet zonder windmolens. Hiervoor heeft Map5 momenteel nog geen icoon. Zou er eentje toegevoegd kunnen worden?

Er staat een interessant icoon voor windmolens op de moderne kaart van [Topotijdreis](https://www.topotijdreis.nl/kaart/2022/@103921,432762,10):
![image](https://github.com/map5nl/map5issues/assets/61314579/9f059269-bfd0-43a0-9dc0-56fb80a75975)

Een minder abstract icoon is ook mogelijk, zoals op [OSM Carto](https://www.openstreetmap.org/#map=17/51.88354/4.64109):
![image](https://github.com/map5nl/map5issues/assets/61314579/4a68bf00-9352-47ba-bbed-6c002e134c24)

De [kaart van de verstedelijking](https://www.cultureelerfgoed.nl/onderwerpen/bronnen-en-kaarten/overzicht/kaart-van-de-verstedelijking) heeft ook een eigen icoon voor windmolens, al is het soort windmolen in deze icoon is niet representatief voor de meeste typen windmolens die we in Nederland hebben.
![image](https://github.com/map5nl/map5issues/assets/61314579/c38effbd-865e-4808-bb63-79cdabe6612a)

Op [Wikimedia Commons](https://commons.wikimedia.org/w/index.php?search=windmill+icon&title=Special:MediaSearch&go=Go&type=image&fileres=%3C500) kwam ik enkele andere iconen tegen, zoals deze: ![image](https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Maki7-windmill-white.svg/15px-Maki7-windmill-white.svg.png)

OpenStreetMap heeft windmolens in de database onder de tag [man_made=windmill](https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dwindmill).

**Comment by justb4** [comment]
Eerste aanzet: Carto icoon.
![image](https://github.com/map5nl/map5issues/assets/582630/630b17f5-76f1-4de8-8337-8eab0bb90db9)

**Comment by justb4** [comment]
Zouden ook windmolens voor stroom opwekking moeten komen, bijv die op Noordzee en Flevoland. Zal meer zijn:
https://wiki.openstreetmap.org/wiki/Tag:generator:source%3Dwind

**Comment by justb4** [comment]
Deze laatste, `power=generator generator:method=wind_turbine` staan er ook op:

![image](https://github.com/map5nl/map5issues/assets/582630/992bec63-d923-4a43-95e3-2590873d4e28)

**Comment by 501Ghost** [comment]
De windturbines zien er wel erg klein uit. Je moet bijna je ogen samenknijpen om ze te herkennen. Windturbines zijn best wel prominent in het landschap en zijn doorgaans alleen omringd door een hek en een veld, dus een groter icoon zou naar mijn idee goed passen en niets anders op de kaart in de weg zitten.

**Comment by justb4** [comment]
Kan idd prominenter: plaatje hierboven is overigens 2x verkleind, maar icoon zelf, gebruik nu de schaalbare SVG-, Carto-iconen, is m.i. te complex, lijkt soms meer op palmboom. Een simpeler icoon zoals deze kan beter voldoen:

![image](https://github.com/map5nl/map5issues/assets/582630/4c9fcc81-1cb6-44ab-986f-2e8583eb4a33)

Nu een zoeken met bruikbare licentie, of zelf maken...

**Comment by 501Ghost** [comment]
Misschien [Wind-turbine - Delapouite - game-icons.svg](https://commons.wikimedia.org/wiki/File:Wind-turbine_-_Delapouite_-_game-icons.svg) of [Wind Farm Icon Symbol.svg](https://commons.wikimedia.org/wiki/File:Wind_Farm_Icon_Symbol.svg)

**Comment by justb4** [comment]
Bedankt, gebruik die van https://game-icons.net nu:

![image](https://github.com/map5nl/map5issues/assets/582630/c515797c-4cfd-495d-b26f-571b71dec659)

**Comment by 501Ghost** [comment]
Dat ziet er goed uit! 👍 

Naar mijn idee kan deze issue nu gesloten worden.
