### ISSUE TITLE
map5topo_zero - een labelvrije kaart op basis map5topo 

### ISSUE THREAD

**Issue by justb4** [map5nl/map5#53]
Dus een map5topo kaart waarin volgende weggelaten:

* text labels, bijv woonplaats/straatnamen

Open vragen, wat nog meer weglaten:

* "shields" bijv weg-nummer-labels
* detail: hillshading
* detail: contourlijnen, met hoogtelabels
* ...

Mijn (justb4) voorstel: map5topo_simple kaart als uitgangspunt (bevat oa geen hillshading en contourlijnen), maar de afnemer mag hier bepalen...

**Comment by MarcovanAntwerpen** [comment]
Qua details (ook na verder inzoomen) de weergave zoals op bijgevoegd screenshot (maar dan zonder tekst labels). 
![image](https://github.com/map5nl/map5issues/assets/31475314/c965f6f0-0c94-4318-a90d-c03d717762f2)

**Comment by justb4** [comment]
Ok, ik zie `map5topo_simple` kaart hier dus als uitgangspunt, dwz sowieso zonder hillshading en contourlijnen. 

Vraag @MarcovanAntwerpen : Ook POI-iconen, bijv kampeerterreinen, kerken, ziekenhuizen weglaten?

**Comment by justb4** [comment]
Op ontwikkelomgeving een eerste resultaat:

![image](https://github.com/map5nl/map5issues/assets/582630/92b21dd3-c78d-4703-b4a0-c6116040e47d)

**Comment by koenschippers** [comment]
Ik vind het er al een stuk rustiger uitzien.
- Bij wat verder uitzoomen verschijnt er een scheepvaartroute vanaf de Noordzee naar Zeebrugge en Vlissingen, deze is overbodig.
-  Op het moment van uitzoomen dat de doorgaande wegen veranderen van geel met een donkere rand naar geel zonder rand worden deze slecht zichtbaar. Wat mij betreft mogen ze dan al verdwijnen.    

voor de rest heb ik geen opmerkingen.

**Comment by Geogoeroe** [comment]
![afbeelding](https://github.com/map5nl/map5issues/assets/9982061/0d0dd351-61ed-48bb-a93a-c12eae7a4bc7)
Er zijn nog wel wat labels die wel getoond worden. Volgens mij met name bij bruggen en tunnels...

**Comment by justb4** [comment]
Good catch: inderdaad labels bij bruggen en tunnels stonden nog "aan". Op ontwikkel omgeving (er zijn 3 omgevingen: dev, test, prod) aangepast:

![image](https://github.com/map5nl/map5issues/assets/582630/20192a92-dd1b-4038-ac33-a4a565c69687)

**Comment by justb4** [comment]
@koenschippers ferry-routes ook verwijderd (rechts):

![image](https://github.com/map5nl/map5issues/assets/582630/1f7906e6-1ff4-4c53-906a-77cc9830cc1f)

Die scheepvaartroute van Zeebrugge etc bij uitzoomen onderzoek ik. Denk dat dit een "waterway" uit OSM (lowzoom) is. Of misschien moeten de ferry-routes, bijv Vlissingen-Breskens, juist blijven?

Ok, begreep comment eerst niet goed (ik verwarde vaarwegen met ferry-routes). De vaarwegen zijn in alle kaarten wat inconsequent: alleen op lage zoom t/m RD 5 zichtbaar, daarna verdwenen, issue voor alle kaarten. Ik laat ze nu even weg op zoom t/m 5 en zet ferry routes, zijn verbindingen net als wegen en treinen, weer terug, dus bij Zeeuws Vlaanderen wordt op 5:

![image](https://github.com/map5nl/map5issues/assets/582630/55894b82-0133-4370-9b06-ab1567ee5cf4)

en op 6 komen de ferry-routes.

**Comment by Geogoeroe** [comment]
Ik zit nog even te kijken, en ik heb een suggestie: de fietspaden (highway=Cycleway) niet weergeven. Niet omdat fietspaden onbelangrijk zijn, maar ze zitten op zich ook al in de vlakkenlaag en geven af en toe wat wonderlijke beelden... 
Eerste plaatje is binnenstad Delft, waar het behoorlijk chaotisch toont en er veel dangles zijn. 
![image](https://github.com/map5nl/map5issues/assets/9982061/0a199ec4-1986-48fd-a429-ae52eb8fc503)
Tweede plaatje is een random stukje Veluwe, omdat het daar heel anders is. Ik keek of fietspaden daar wél belangrijk zijn, maar ook daar is het dubbelop. En omdat ze apart van de vlakken zijn ingewonnen meanderen ze door elkaar heen...
![image](https://github.com/map5nl/map5issues/assets/9982061/e6b7498d-a319-48e5-9c6f-1b0ff9c48a19)

**Comment by justb4** [comment]
@Geogoeroe fietspaden (en wandelpaden): staat sowieso nog issue, intern, voor open voor alle kaarten. Wat we hier zien is de "mismatch" tussen data uit BRT, BGT (vlakken) en OSM (lijnen), ook afhankelijk van het RD zoomnivo:

* t/m 12 terreinvlakken BRT, geen wegdelen, mn Top10NL
* 13 alle vlakken, ook wegdelen, uit BGT

Op beide levels wegen, paden via lijnen uit OSM. Dit probleem speelde ook bij OpenTopo: daar ook tussen BRT (Top10) en BGT, m.n. in buitengebieden. Zie bijv dit voorbeeld Lage Vuursche bij Baarn:

![image](https://github.com/map5nl/map5issues/assets/582630/c0bc3046-4c09-4232-8719-bd51de22b5c6)

* Links  BGT (wit) Wegvlakken en OSM paden (paars is MTB). 
* Rechts BGT (wit) en Top10NL (bruin gestippeld) wegvlakken

Mismatch tussen BGT en BRT zal in toekomst met BRT.Next opgelost moeten worden. In OSM is vaak nog van "3DShapes", voorloper BRT gebruik gemaakt. 

Maar lang verhaal kort: het beeld wordt rustiger als we de paths weglaten, alleen mis je dan heel veel paden, bijv fietspaden,  waar weer geen BGT vlakken onder liggen. Dat is vooral in buitengebied best veel. Is dus algemeen dilemma. Maar blijft dat OSM qua wegen en vooral paden het meest compleet en actueel is.  Vandaar die keuze. 

Alle data komt uiteindelijk uit het geïntegreerde "map5 data model/schema", gemengd uit Basisregs+OSM, zie https://map5topo.nl/design/data/. Daarin zit ook voor ieder object/record, haar oorsprong. 

De hamvraag is: moet in map5topo_zero het volledige wegen-netwerk, inclusief wandel, fiets/MTB paden behouden blijven? Indien niet, is het redelijk gemakkelijk om wandel, fiets/MTB paden weg te laten. Deze zijn allen geclassificeerd als `"lod1=trail"`. Zeg maar, lijkt mij ook wel meer rust in kaart geven.

**Comment by geertoff** [comment]
Hallo Just, 

Ziet er al heel gaaf uit! Als het uitgangspunt van Map5TopoZero een achtergrondkaartlaag die simpeler en rustiger is dan Map5TopoSimple, dan lijkt het mij tof als de patronen in vlakken bij een hoog zoomniveau (grotere schaal), zoals in het bos, uitstaan. Vanaf zoomniveau 9 staan ze nu aan. 

Om alsnog de onderscheiding tussen (in dit geval soorten bossen) te maken, zou een andere kleur voor het type bos misschien een idee zijn. Zoals onderstaande screenshot. 
![map5zero_suggestie](https://github.com/map5nl/map5issues/assets/102165826/50856bda-999b-48a9-8f06-de1e01e87248)
Hetzelfde geldt voor andere type patronen.

**Comment by justb4** [comment]
@Geogoeroe @geertoff goede suggesties, kunst van weglaten. Uitgeprobeerd op Dev (rechts): alle Roads "trails" (gestreepte fiets/wandel paden) en Landcover overlay groenpatronen (bos, gras etc) weggelaten:

![image](https://github.com/map5nl/map5issues/assets/582630/e838ee31-5ff4-4273-9c72-2b8398ee293b)

en Delft:

![image](https://github.com/map5nl/map5issues/assets/582630/e504c056-b524-4f00-a17a-5c3e955fe924)

**Comment by justb4** [comment]
@koenschippers weglaten van "secondary" roads (geel zonder rand) op zoom <  RD 6 werkt goed (rechts):

![image](https://github.com/map5nl/map5issues/assets/582630/a3f94b14-f6e1-44b3-9f6d-837163661253)

**Comment by Geogoeroe** [comment]
> De hamvraag is: moet in map5topo_zero het volledige wegen-netwerk, inclusief wandel, fiets/MTB paden behouden blijven? Indien niet, is het redelijk gemakkelijk om wandel, fiets/MTB paden weg te laten. Deze zijn allen geclassificeerd als `"lod1=trail"`. Zeg maar, lijkt mij ook wel meer rust in kaart geven.

Ja, ik denk dat het een idee is om die paden weg te laten, maar we zouden even kunnen kijken in welke gevallen ze echt iets bijdragen bij gebruik als een achtergrondkaart (want daar is de zero-kaart m.i. met name voor bedoeld). Als we geen gevallen zien waar het wél echt belangrijk is dan zou ik ze idd skippen.

**Comment by koenschippers** [comment]
> Ik vind het er al een stuk rustiger uitzien.
> 
> * Bij wat verder uitzoomen verschijnt er een scheepvaartroute vanaf de Noordzee naar Zeebrugge en Vlissingen, deze is overbodig.
> * Op het moment van uitzoomen dat de doorgaande wegen veranderen van geel met een donkere rand naar geel zonder rand worden deze slecht zichtbaar. Wat mij betreft mogen ze dan al verdwijnen.
> 
> voor de rest heb ik geen opmerkingen.

@justb4, dat de veerdiensten eruit zijn vind ik prima maar met scheepvaartroutes doelde ik eigenlijk op de blauwe aaneengesloten lijnen uit onderstaande afbeelding.
 
![image](https://github.com/map5nl/map5issues/assets/148458118/2b5958d1-abf2-4106-8e8e-6fc7ed88d942)

**Comment by justb4** [comment]
Op de test server is een nieuwe versie. Bedoeling is deze versie naar productie (maandelijks), ivm overige lagen beschikbaar. dit is de status mbt commentaren hierboven:

 - [x] remove road names bridges/tunnels @Geogoeroe rel. 2023-12 
 - [x] remove vaarroutes @koenschippers rel. 2023-12 
 - [x] remove ferry routes  (veerdienst routes) @koenschippers  rel. 2024-1 
 - [x] remove secondary roads (yellow) at zoom 5 and less @koenschippers rel. 2023-12 
 - [x] no patterns for landcover like trees and grass @geertoff rel. 2023-12 
 - [ ] OPTION: different green colours for tree types (needle-, broadleaved, mixed)  @geertoff  rel. 2024-1 
 - [x] remove all dashed paths: footpaths, cycleways, MTB etc @Geogoeroe rel. 2023-12 
 - [x] remove wetland and swamp patterns (landcover over water) rel. 2024-1 

* rel. 2023-12 begin jan 2024
* rel. 2024-1 begin feb 2024

**Comment by MarcovanAntwerpen** [comment]
Hoi Just,

Is er misschien ook een link die in QGIS geladen kan worden? Dan kunnen we ook testen hoe het over komt als we het plotten op A0.
We hebben vaak van die gedeputeerden die een mooie wandkaart willen.
Bedankt alvast!

Groet, Marco

Van: Just van den Broecke ***@***.***>
Verzonden: zaterdag 6 januari 2024 18:27
Aan: map5nl/map5issues ***@***.***>
CC: Antwerpen v M. (Marco) ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [map5nl/map5issues] map5topo_zero - een labelvrije kaart op basis map5topo (Issue #53)


Op de test server is een nieuwe versie. Bedoeling is deze versie naar productie (maandelijks), ivm overige lagen beschikbaar. dit is de status mbt commentaren hierboven:

  *   [X] remove road names bridges/tunnels @Geogoeroe<https://scanmail.trustwave.com/?c=21408&d=-I2Z5dakIBGDL5cnv68ZKFcVU9ZYzdH-Wj4pPZ2FUg&u=https%3a%2f%2fgithub%2ecom%2fGeogoeroe>
  *   [X] remove vaarroutes @koenschippers<https://scanmail.trustwave.com/?c=21408&d=-I2Z5dakIBGDL5cnv68ZKFcVU9ZYzdH-WjtyZ53TCg&u=https%3a%2f%2fgithub%2ecom%2fkoenschippers>
  *   [ ] remove ferry routes (veerdienst routes) @koenschippers<https://scanmail.trustwave.com/?c=21408&d=-I2Z5dakIBGDL5cnv68ZKFcVU9ZYzdH-WjtyZ53TCg&u=https%3a%2f%2fgithub%2ecom%2fkoenschippers>
  *   [X] remove secondary roads (yellow) at zoom 5 and less @koenschippers<https://scanmail.trustwave.com/?c=21408&d=-I2Z5dakIBGDL5cnv68ZKFcVU9ZYzdH-WjtyZ53TCg&u=https%3a%2f%2fgithub%2ecom%2fkoenschippers>
  *   [X] no patterns for landcover like trees and grass @geertoff<https://scanmail.trustwave.com/?c=21408&d=-I2Z5dakIBGDL5cnv68ZKFcVU9ZYzdH-WjF4Zs7UCA&u=https%3a%2f%2fgithub%2ecom%2fgeertoff>
  *   [ ] OPTION: different green colours for tree types (needle-, broadleaved, mixed) @geertoff<https://scanmail.trustwave.com/?c=21408&d=-I2Z5dakIBGDL5cnv68ZKFcVU9ZYzdH-WjF4Zs7UCA&u=https%3a%2f%2fgithub%2ecom%2fgeertoff>
  *   [X] remove all dashed paths: footpaths, cycleways, MTB etc @Geogoeroe<https://scanmail.trustwave.com/?c=21408&d=-I2Z5dakIBGDL5cnv68ZKFcVU9ZYzdH-Wj4pPZ2FUg&u=https%3a%2f%2fgithub%2ecom%2fGeogoeroe>

Uitstaande kunnen met rel. 2024-1 (begin feb 2024) mee.

**Comment by justb4** [comment]
remove wetland and swamp patterns (landcover over water) rel. 2024-1 dus (rechts):

![image](https://github.com/map5nl/map5issues/assets/582630/6f5a12ef-1d4f-417e-b150-4445a246912d)

**Comment by justb4** [comment]
Gedaan, en geaccepteerd, voor verdere verbeteringen/issues, graag nieuw issue openen.
