### ISSUE TITLE
HQ tiles hebben wat randissues, zeker met labels

### ISSUE THREAD

**Issue by Geogoeroe** [map5nl/map5#55]
Geen uitgebreide check gedaan, maar dit ziet er niet helemaal uit zoals ik het zou verwachten (in QGIS en Tailormap getest, zelfde beeld).

![afbeelding](https://github.com/map5nl/map5issues/assets/9982061/d7370d18-a25e-444a-b280-64716334f86c)

**Comment by justb4** [comment]
Confirmed, viewer maakt sowieso niet uit. Dit heeft met tile-rendering te maken. Labels moeten natuurlijk niet afgekapt op randen van de tile. Daartoe zijn een drietal mechanismen: in de renderer (Mapnik) stijl regels, via "metatiling" (tijdens tilen grotere gebieden tilen, NxN tiles, en dan opsnijden) en tenslotte "buffering/gutter" (extra rand om (meta)tile). En dan kan het toch gebeuren dat het "fout" gaat, al moet ik zeggen, zeer zelden.

We doen een onderzoek nu, omdat met name "buffering" misschien toch niet gewenste resultaat geeft. Ik heb een vraag hierover uitstaan [1], want eerlijk gezegd, snap ik niet wat er gebeurt, of dat het toch iets specifieks is voor bij WMS. lHeb helaas nog geen antwoord, misschien weet iemand bij jullie dat. Metatiling snap ik, maar die buffer...

[1] https://lists.osgeo.org/pipermail/mapproxy/2024-April/003112.html

**Comment by justb4** [comment]
Grotere buffer/gutter levert wel goede resultaten, is toch wat mysterieus hoe dat werkt.
Oorspronkelijke waarde was `buffer: 64`, maar variatie heeft zeker effect:

* `buffer: 0` als bovenstaand resultaat (afkappingen)
* `buffer: 128` idem
* `buffer: 256` geen afkappingen, zie plaatje onder

<img width="1536" alt="image" src="https://github.com/map5nl/map5issues/assets/582630/f2f2f205-2d3e-4612-9b25-a8b2bfb790b0">

De metatile is 2x2 dus gebied width of height is 2x512+2x256=1536 pixels (was 2x512+2x64=1152). Natuurlijk wil je zo groot mogelijk gebied ophalen, maar de limitatie gaat ook in de grootte van de query zitten, dat lijkt vaak de bottleneck...
We gaan kijken...

**Comment by justb4** [comment]
Er was nog een case (via Prov. Zeeland), "Vlissingen" afgekapt op zoom RD7:

<img width="801" alt="image" src="https://github.com/map5nl/map5issues/assets/582630/4cb81940-ffae-4fba-bee4-17db455c2171">

die is ook hiermee gerepareerd:

<img width="1023" alt="image" src="https://github.com/map5nl/map5issues/assets/582630/65677e64-c3be-415d-bf08-df7326298dd2">

**Comment by Geogoeroe** [comment]
Nou ja, als die buffer dezelfde waarde heeft als bij de reguliere tiles dan snap ik dat het wat mis kan gaan. Maar als een factor 2 het probleem niet oplost bij een 2x zo grote X of Y per tegel, dan is dat (voor mijn lineaire brein) wel wat apart. Anyway, blij dat het wel strak kan.

**Comment by justb4** [comment]
Hier staat het uitgelegd: https://mapproxy.github.io/mapproxy/latest/labeling.html#meta-buffer
Maar dan nog, ik begrijp niet hoe die buffer, zonder WMS, wordt afgebeeld op de uiteindelijke 512x512 tiles.  Maar de grootte moet in ieder geval minimaal de helft van de maximale label-lengte zijn. Ik ga ook nog kijken naar de stijlen, die bepalen algoritme voor plaatsing alle labels (want er zijn labels in meerdere lagen, bijv huisnummers).

**Comment by Geogoeroe** [comment]
Overigens, voor Vlissingen is de buffer mogelijk nu iets te groot: ik zie een dieptelijn met een extra 0 erin, direct bij de uitgang van de haven.

**Comment by justb4** [comment]
Ja we zijn nog niet klaar. Het is 1 getal voor alle zoomlevels. In Mapnik kun je zelfs buffer per laag aanzetten, de dieptelijnen bijv. Maar, dat was ook mijn vraag, weet MapProxy daar mogelijk niet van.

**Comment by justb4** [comment]
Zoals ik zei, er zijn nog veel meer knoppen/wielen, om aan te draaien, zoals de (Mapnik) Style [TextSymbolizer](https://github.com/mapnik/mapnik/wiki/TextSymbolizer):
`label-position-tolerance="50"` ipv `"100"`, maar ook `avoid-edges:` (lijkt geen effect te hebben).  Later meer: *"In een blauw geruite kiel / Draaide hij aan 't groote wiel"* kwam ineens in mij op....

<img width="800" alt="image" src="https://github.com/map5nl/map5issues/assets/582630/4e35658a-2aca-469e-b4af-11e6132b8586">

**Comment by justb4** [comment]
De nieuwe map5topo versie 2024-04 is uit. Veel label issues verdwenen. Alleen is helaas de 256 pixel gutter, die vooral "Vlissingen" verschil maakte, niet in productie configuratie meegekomen, maar nog steeds 64 px. De afkappingen blijven zeldzaam maar ik verwacht zo goed als weg in v 2024-05 (juni).

**Comment by justb4** [comment]
@Geogoeroe 2024-05 is net uit, alle bovenstaande "label-afkap" issues zijn m.i. opgelost. Dan dit issue sluiten.
