### ISSUE TITLE
Meetlat

### ISSUE THREAD

**Issue by rvbdordrecht** [map5nl/map5#6]
Misschien de optie een klein meetlatje in beeld te brengen waarmee zoomlevel / afstand in meters zichtbaar is.

**Comment by justb4** [comment]
ja nuttig. Was "one-liner" om de standaard Leaflet Scalebar te aktiveren: zie  http://app.test.map5.nl/nltopo. Op kleinere schermen zit de attributie tekst in de weg.  Alleen om dit via optie te doen en zoomlevel tonen is een volgende stap.

**Comment by rvbdordrecht** [comment]
Hoi Just,

Ik zie inderdaad onder de tekst de afstand staan.
Nu ik dat weet, kan ik het toch wel vinden. Je hebt het ook niet permanent
nodig natuurlijk.

Bedankt voor de uitleg.

Groet,
René

**Comment by rvbdordrecht** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- René

Confirm that you know René: https://www.linkedin.com/e/v2?e=huz1y8-i9skhbbk-4f&amp;a=preRegInvite&amp;tracking=eml-guest-invite-cta&amp;ek=invite_guest&amp;sharedKey=bUvVj1Oi&amp;invitationID=6005712503957393408


You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=huz1y8-i9skhbbk-4f&amp;t=lun&amp;midToken=AQFmrFVhGEd36Q&amp;ek=invite_guest&amp;loid=AQFyldfUHYzivgAAAU1iT1pQFFKaZWepX5ZLWQvm2aFiANceLH1j6QSPuzEu0Jegn2ixE2i17NDraeD4LMQsatNDt5Z7e9FCwWsLTBldjDYaDqUWwpkSQEt1Z5lfhmyxrbmIyVyFGTKQM7YMFa8KJgxPBDERhrdVBvzCcDgQgiMVIGBzNP1QUjOFXpMWk9oKrXzr&amp;eid=huz1y8-i9skhbbk-4f Learn why we included this at the following link: https://www.linkedin.com/e/v2?e=huz1y8-i9skhbbk-4f&a=customerServiceUrl&ek=invite_guest&articleId=4788
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by justb4** [comment]
@rvbdordrecht Ik weet niet hoe je LinkedIn uitnodiging hier terecht is gekomen, maar accepteer verzoek graag. Ik sluit de issue voorlopig. Open evt nieuwe issue voor verbetering. De hele app wordt sowieso vernieuwd om gemakkelijker opties toe te voegen (menu, settings knop etc). NB zoomlevel gaat ook omhoog (zag geen issue).

**Comment by rvbdordrecht** [comment]
Goedemiddag,

Bedankt voor je mail.
Ik heb juist mijn Linkedin gedeactiveerd, maar blijkbaar heeft de app nog
even snel al mijn contacten een mail gestuurd. Heel vervelend.

Altijd mooi om te horen dat een app wordt doorontwikkeld. Wanneer kunnen we
de update verwachten? Ben ook wel heel benieuwd wat er met het zoomniveau
gaat gebeuren. Meer details?? Ik ben en pixel freak, dus het klinkt goed.

Hoor het graag van je.

Groet,
René

**Comment by justb4** [comment]
Hallo René, ja kreeg error op LinkedIn. En ja er komt een zoomlevel bij. 
groet, Just

**Comment by rvbdordrecht** [comment]
Geweldig!
Wanneer verwacht je de update?
Kan ik het een beetje in de gaten houden.

Alvast bedankt,
Groet,
René

**Comment by justb4** [comment]
Ik ben bezig met release 15.5, de NLTopo App bevat als het goed is nu 1 
zoomlevel meer. Alles staat klaar via http://www.map5.nl, inclusief 2 
nieuwe lagen relief_struct en openlufo,. De opentopo-laag is nu met JPEG 
tiles: scherper en kleinere files.

De lagen zijn nog aan het tilen dus e.e.a. kan vertragen.

**Comment by rvbdordrecht** [comment]
Goedenavond,

Het viel me op dat de altijd zichtbare knoppen het kaartbeeld nogal
verstoren. Ze zijn erg prominent in beeld.

Ik ben zelf groot fan van het Material Design in Android 5.0. Er zou dan
rechts onderin een FAB ( floating action button ) zichtbaar zijn, waarmee
je de knoppen kan oproepen.
Ik stuur je twee screenshots van de werking van de FAB.

Zou prachtig zijn om te implementeren!!
Reliëfkaarten zijn geweldig!

Groet,
René.

**Comment by justb4** [comment]
Bedankt voor de suggesties! De app gaat zeker verbeterd worden qua menu/knoppen. Kun je gewenste verbeteringen als nieuwe issues hier openen? Dan zijn ze zichtbaar en traceerbaar. Er zijn net 2 nieuwe faciliteiten bijgekomen: zie issue #13 en issue #12.

**Comment by rvbdordrecht** [comment]
Bij de app voor Android biedt Material Design een goede mogelijkheid om alle knoppen uit het kaartbeeld te laten verdwijnen.

Door gebruik te maken van en FAB ( floating action button ) kun je alle opties " verbergen " achter deze knop. Je krijgt dan een full screen beeld zonder verstoringen.

Inzoomen kan op een mobiel al met " double tap " en/ of " pinch to zoom " dus de + en. - knoppen kunnen zonder problemen achterwege blijven.

**Comment by rvbdordrecht** [comment]
Zijn de issues nu op de juiste plek?
In Github is het voor mij niet echt duidelijk hoe een nieuwe case aan te
maken!

Groet

**Comment by rvbdordrecht** [comment]
Goedemiddag,

Ik heb de developer van Locus Maps gemaild of hij Open Topo maps kende.
Jullie kaarten zouden prachtig binnen hun concept passen.

Hij zou contact met je opnemen over het gebruik van jullie kaarten.

Lijkt me een prachtige combi, want met de web versie van Opentopo kun je
niet echt navigeren in het open veld. Met Locus zou daar wel kunnen.

Hoop dat jullie elkaar vinden.

Groet,
René

**Comment by justb4** [comment]
Hallo René, Bedankt! Ik heb Locus Maps bekeken, is heel veelzijdig. Ik hoop van ze te horen. Overigens kun je ook een Persoonlijk Abbo URL voorzien van Map5 Key  invoeren in bijv Locus Maps (helaas alleen WMS), maar ook vele andere mobiele apps. Ikzelf gebruik bijv al jaren Backcountry Navigator (Pro) (ondersteunt XYZ Tiling), zie screenshot.
 
![screenshot_bcn-app1](https://cloud.githubusercontent.com/assets/582630/8271384/f13a65ec-1814-11e5-9cbe-aa45e721943a.png)

**Comment by rvbdordrecht** [comment]
Goedemiddag Just,

Ik ben heel benieuwd hoe het staat met de ontwikkeling van de  Opentopo
Android app.

Ik gebruik nog steeds heel vaak je app.map5.nl/nltopo website, maar een app
zou deze fantastische kaarten toch wel een grote meerwaarde geven.

Hoor het graag van je, terwijl ik besef hoe verschrikkelijk veel werk het
waarschijnlijk is!

Groet,
René

**Comment by justb4** [comment]
Hallo René, De Android  app loopt nog niet zo hard, wel bezig om bijv GPX files te laden, nu nog lokaal: zie bijv http://app.map5.nl/nltopo/?key=gast&gpx=gpx/vliegenbos238.gpx 
We hebben wel een nieuwe release van de OpenTopo kaarten (2015-R06) en een nieuwe laag OpenSimpleTopo.

Groet,

Just

PS kun je anders email gebruiken voor directe vragen? Dit zijn nu commentaren in een gesloten issue in GitHub...
