### ISSUE TITLE
Reliëfkaart (hillshading map) Nederland gewenst

### ISSUE THREAD

**Issue by justb4** [map5nl/map5#7]
Verschillende klanten hebben aangegeven dat de reliëfkaart die nu in OpenTopo zit, als losse kaartdienst gewenst is. De reliëfkaart wordt met AHN2 samengesteld. Het zou als een transparante overlay kunnen dienen voor bijv archeologisch onderzoek op andre kaarten. 

Mogelijk nog varianten met/zonder gebouwen? Water is ook een issue. En transparantie (hoeveel?). Aangehecht een voorbeeld door JW van Aalst, met water opgevuld en vlakken/gebouwen op 90% transparantie. Misschien teveel detail voor een overlay, meer transparantie nodig? (Hoewel dat ook in viewers zoals http://kadviewer.kademo.nl kan). 

![ahn2-relief-water](https://cloud.githubusercontent.com/assets/582630/7452813/aeba2e50-f262-11e4-8387-245e9a031868.jpg)

**Comment by jwva** [comment]
Wat bedoel je met 'transparantie'? Ik neem aan dat je een overlay met elke gewenste transparantie kunt plaatsen?

**Comment by justb4** [comment]
@jwva : Ja in een moderne viewer wel, maar niet iedereen kan dit, dus zitten ze vast aan transparantie van de bronkaart. Het gaat om die transparantie. Ik denk dat het meer gaat om weglaten terreinvlakken zodat je alleen hillshades+water overhoudt? Dan is overal waar geen hillshade voorkomt automatisch transparant (nodata). Dan kun je de kaart bijv over een ge-georefereerde historische kaart leggen om zodoende oude structuren te onderzoeken. Maar daar kunnen anderen hopelijk meer over zeggen. Mogelijk kun je hier een voorbeeld aanhechten met bovenstaande reliëfkaart zonder terreinvlakken?

**Comment by jwva** [comment]
Hoi, ik vrees dat dat niet gaat werken. De terreinvlakken weghalen resulteert niet in meer of minder transparantie; de kaart wordt alleen grijzer (minder kleur), da's alles. Overal waar in Top10 een terreinvlak is, zit in AHN2 ook een pixel. Dus als ik terreinvlak uitzet, heb je nog steeds AHN2 data. Frank heeft alle gaten dichtgemetseld. De 'nodata' in de AHN2 is alleen zoveel meter vanaf de kustlijn en landsgrens.

**Comment by justb4** [comment]
Ok, ik had voor ogen de hillshading kaart zoals op
http://hiking.waymarkedtrails.org/
Daar kun je, middels de "settings"-knop onder, de transparantie van de hillshading overlay instellen.
Deze is niet op AHN2 gebaseerd, dus heel grof, maar gaat om idee. De overlay tiles kennen veel transparantie, bijv http://tile.waymarkedtrails.org/hillshading/14/8467/10974.png (en aangehecht).

![hillshade-example-lonvia de](https://cloud.githubusercontent.com/assets/582630/7453699/5fa62706-f26c-11e4-869e-609732804fac.png)

**Comment by jwva** [comment]
Ik verwacht inderdaad van een moderne app dat je de transparantie van een overlay kunt instellen. Maar het transparant maken gebeurt dan dus aan de kant van de app, niet in de graphics zelf.

**Comment by justb4** [comment]
Voor release 15.5 komt er 1 enkele relief laag: Relief met lichte structuren uit OpenTopo `relief_struct` geheten.  De composiet zal als volgt worden:

	LAYER
	  NAME "relief_struct_37_5"
	  GROUP "relief_struct"
	  CLASS
	     MINSCALEDENOM 100000
	  END
	END

	LAYER
	  NAME "relief_struct_400"
	  GROUP "relief_struct"
	  CLASS
	   MAXSCALEDENOM 100000
	   MINSCALEDENOM 10000
	  END
	END

	LAYER
	  NAME "relief_struct_1600"
	  GROUP "relief_struct"
	  CLASS
	   MAXSCALEDENOM 10000
	  END
	END

Zie ook issue #10: JPEG encoding zal gedaan worden, zie plaatje waarom:

![relief_struct-png-vs-jpeg](https://cloud.githubusercontent.com/assets/582630/7698880/0e3659a0-fe14-11e4-8c67-9f169d61134f.png)

**Comment by jwva** [comment]
Als je de relief_struct gaat aanbieden als overlay, bied dan 30% opacity (voor het 'opentopo' shading effect) of 38% en 62%, met knipoog naar de heilige geometrie  ;-)

**Comment by justb4** [comment]
On 19-05-15 17:32, jwva wrote:
> Als je de relief_struct gaat aanbieden als overlay, bied dan 30% opacity
> (voor het 'opentopo' shading effect) of 38% en 62%, met knipoog naar de
> heilige geometrie ;-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/map5nl/map5/issues/7#issuecomment-103554108>.
>
Dit is een instelling binnen de NLTopo-app niet van de kaart zelf, en is 
al gerealiseerd. Komt mee in volgende versie: 
https://github.com/map5nl/map5/milestones/Versie%2015.5

**Comment by justb4** [comment]
Gedaan in release 15.5.
